---
# - name: update repo and cach
#   hosts: devza
#   tasks:
#     - name: Update apt repo and cach
#       apt: 
#         update_cache: yes
#         force_apt_get: yes 
#         cache_valid_time: 3600

      # - name: install aptitude using apt
      #   apt: update_cache=yes name=aptitude state=latest force_apt_get=yes

- name: install docker & minikube & kubectl
  hosts: devza
  vars_files:
    - bp_vars.yaml
  tasks:
    # - name: install pip
    #   command: apt install python-pip -y

    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Add Docker Repository
    #   apt_repository:
    #     repo: deb https://download.docker.com/linux/ubuntu bionic stable
    #     state: present

    # - name: Update apt and install docker-ce
    #   apt: update_cache=yes name=docker-ce state=latest
    # - name: install docker-py
    #   command: pip install docker

    # - name: donload minikube
    #   get_url:
    #     url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    #     dest: /tmp
    #     mode: +x

    # - name: mv minikube
    #   command: mv /tmp/minikube-linux-amd64 /usr/local/bin/minikube
    # - name: download kubectl
    #   command: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.1/bin/linux/amd64/kubectl
    # - name: chmode kubectl
    #   command: chmod +x ./kubectl
    # - name: mv kubectl to bin
    #   command: mv ./kubectl /usr/local/bin/kubectl
    # - name: start minikube
    #   command: minikube start --force

    # - name: check repo if exist
    #   stat:
    #     path: "/root/project1"
    #   register: project1
    # - name: clone repo and change dir
    #   command: git clone https://github.com/hchorfi/node-hello.git project1
    #   when: not project1.stat.exists

    # - name: build jenkins image as code
    #   command:  chdir=/root/project1/jenkins/jcasc docker build -t jenkins:jcasc .

    - name: clone repo from github
      git:
        repo: https://github.com/hchorfi/Devops_p1.git
        dest: /root/project1

    - name: build jenkins image
      docker_image:
        name: jenkins
        tag: jcasc
        build:
          path: /root/project1/jenkins/jcasc
        source: build
        nocache: yes

    - name: start jenkins container
      docker_container:
        name: jenkins
        image: jenkins:jcasc
        recreate: yes
        state: started
        detach: yes
        privileged: yes
        user: 0
        env:
          JENKINS_ADMIN_ID: "Devza"
          JENKINS_ADMIN_PASSWORD: "password"
        published_ports:
          - "8080:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker
      async: 120
      poll: 0